- name: downloading redis repos
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: installing redis package
  ansible.builtin.package:
    name: redis-6.2.7
    state: present

- name: search and replace ip address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - "/etc/redis.conf"
    - "/etc/redis/redis.conf"
  notify: Restarting service

# - name: Updating redis-6.2.7 Config
#   ansible.builtin.replace:
#     path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
#     regexp: '127.0.0.1'
#     replace: '0.0.0.0' 
#   notify: Restarting service

- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}