- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - demo-vars.yaml
  vars_prompt:
    - name: URL
      prompt: Enter URL value
      private: false    # if we specify we can see what been typed on the command line

  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: "{{ URL }}"

    - name: Printing local variable
      ansible.builtin.debug:
        msg: printing local variable {{ URL }}
      vars:
        URL: local.google.com

    - name: printing client url
      ansible.builtin.debug:
        msg: printing client url {{ CLI_URL }}


# How do your print a variable in bash ????  ${varName}
# To print a vairable in yaml, we will {{varName}}

# Varaible name has to be enclosed in quotes only if it's the only entity in the msg, if not you don't have to place them in quotes. 
# Always prefer to keep the task name different ; In version, it used to throw error. In version 7, that's deprecated.

# Ansible throws you an error if you use a variable that is not declared  ; In bash, it assume it as a empty variable.


# CLI Variables > Local Varaible  > files variables >   Global Variable   > Prompt variable