- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - demo-vars.yaml
  vars_prompt:
    - name: URL
      prompt: Enter URL value
      private: false

  tasks:
    - name: Printing URL
      ansible.builtin.debug:
        msg: "{{ URL }}"

    - name: Printing local variable
      ansible.builtin.debug:
        msg: printing local variable {{ URL }}
      vars:
        URL: local.google.com