#  A fact is nothing but a property of the machine / node extracted by the ansible server.

- name: Demo on facts   
  hosts: all 
  tasks:
    # - name: ansible facts printing
    #   ansible.builtin.debug:
    #     vars : ansible_facts

    - name: task1 
      ansible.builtin.debug:
        msg: OS Distribution = {{ansible_distribution}}

    - name: printing mac address 
      ansible.builtin.debug:
        msg: Mac address is {{ansible_default_ipv4.macaddress}}

- name: Demo on facts mine
  hosts: prod
  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: Os distribution = {{ ansible_distribution }}